CREATE TABLE pa_admin (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  verify BOOLEAN NOT NULL DEFAULT FALSE,
  fullname VARCHAR(250) NOT NULL,
  employment_id VARCHAR(50) UNIQUE NOT NULL,
  office varchar(50) NOT NULL,
  image BYTEA DEFAULT NULL
);

CREATE TABLE pa_users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  verify BOOLEAN NOT NULL DEFAULT FALSE,
  password VARCHAR(100) NOT NULL,
  fullname VARCHAR(250) NOT NULL,
  employment_id VARCHAR(50) UNIQUE NOT NULL,
  office varchar(50) NOT NULL,
  image BYTEA DEFAULT NULL
);
